export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const SAVE_PRESCRIPTION = "SAVE_PRESCRIPTION";
export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
